apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgeclaw.fullname" . }}
  labels:
    {{- include "edgeclaw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ecnpPort }}
      targetPort: ecnp
      protocol: TCP
      name: ecnp
    - port: {{ .Values.service.webuiPort }}
      targetPort: webui
      protocol: TCP
      name: webui
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
      name: websocket
  selector:
    {{- include "edgeclaw.selectorLabels" . | nindent 4 }}
